# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94da1a9f690d20218a4bb91bf38fab8241062b25b743fdc2d7254e7da4bd66f03335dba71af793ba4b0d9e4f43352b21c05adff92a0a86cef05a98bf129f71a3

test:
  secret_key_base: ebbdc606d91a45f070f3511f2b7ee9aa16f74b1e014573447f4d547985646cf21ff54cb3243111ebadfd0458b87c401fb805c777a3f071d9780275d2bcfd5ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
