# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dd2025a989fae2e85d9e40ee948bbccee6240f698e35791d75842338cfc46a983564c1bcc6a047f91104f94fcf05a5e314786c04b72c1b987d51140d3fcd3e

test:
  secret_key_base: 1c8ccb12d961d426972929bf342513351ed7e7687dcdb58e06295e0f2a4be2b9aa6ac6597eb0b6daf1ef79d5ae8a060546f4fe912bdeb0656ba0c691291e7e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
